name: push-release
on:
  push:
    tags:
      - v*
jobs:
  push-release:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      REPOSITORY: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REPOSITORY }}
          tag-latest: false

      - name: Push to GitHub Container Registry
        if: github.repository_owner == 'k8snetworkplumbingwg'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:stable-amd64
            ${{ steps.docker_meta.outputs.tags }}-amd64

      - name: Create manifest for multi-arch images
        if: github.repository_owner == 'k8snetworkplumbingwg'
        run: |
          docker manifest create ${{ env.REPOSITORY }}:stable ${{ env.REPOSITORY }}:stable-amd64
          docker manifest annotate ${{ env.REPOSITORY }}:stable ${{ env.REPOSITORY }}:stable-amd64 --arch amd64
          docker manifest push ${{ env.REPOSITORY }}:stable
          docker manifest create ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-amd64
          docker manifest annotate ${{ steps.docker_meta.outputs.tags }} ${{ steps.docker_meta.outputs.tags }}-amd64 --arch amd64
          docker manifest push ${{ steps.docker_meta.outputs.tags }}

